apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service-deployment
  labels:
    app: promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
      - name: promotion-service
        image: truongdocker1/bookstore-promotion-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: APP_JWT_KEYS_DIR
          value: "/key"
        - name: APP_JWT_PUBLIC_KEY_FILE
          value: "public.pem"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: promotion-service-secret
              key: DB_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: promotion-service-secret
              key: DB_PASSWORD
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: SPRING_RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: SPRING_RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: SPRING_RABBITMQ_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: promotion-service-secret
              key: SPRING_RABBITMQ_PASSWORD
        - name: SPRING_RABBITMQ_VIRTUAL_HOST
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: SPRING_RABBITMQ_VIRTUAL_HOST
        - name: CLIENTS_BOOK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: promotion-service-config
              key: BOOK_SERVICE_URL
        volumeMounts:
        - name: jwt-keys
          mountPath: /key
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-keys
          items:
          - key: public.pem
            path: public.pem
